//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaishakanri.Mode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaishajouhou
    {
        public string ID { get; set; }
        public string Kaishaname { get; set; }
        public string Daihyoumei { get; set; }
        public string Denwa { get; set; }
        public string Fax { get; set; }
    }
}
